[[pages]]
path = "dashboard.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Data Alumni"
icon = "ğŸˆï¸"
is_section = true

# Pages after an `is_section = true` will be indented
[[pages]]
path = "pages/Profile.py"
name = "Profil Sebaran Alumni"
icon = "ğŸ’ª"